### ISSUE TITLE
Create Release and add to Library Index

### ISSUE THREAD

**Issue by mariopesch** [sensebox/SolarChargerSB041#1]
@BjoernLuig can you also create a release and add the library to the arduino library index: https://github.com/arduino/library-registry

Adding it to the library index makes it easier to handle in the compiler.

**Comment by BjoernLuig** [comment]
Done

![image](https://github.com/user-attachments/assets/14e1119d-1231-4bb0-be3c-a94a3aee7ab2)

**Comment by BjoernLuig** [comment]
See above
